#!/bin/bash
cd /opt
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
chmod 777 apache-tomcat-9.0.65.tar.gz
tar -xzvf apache-tomcat-9.0.65.tar.gz
cd apache-tomcat-9.0.65/
cd bin
yum install java -y
cd ..
cd bin
./startup.sh




Paste the above commands in EC2-User data field.
